project_id = "jsizmudnvqrrszbnczzf"

[functions.delete-user]
verify_jwt = false

[functions.create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-solicitacao]
verify_jwt = false
